name: Snapshot Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Snapshot Release
    runs-on: ubuntu-latest
    if: "github.event.release.prerelease"
    steps:
      - uses: actions/checkout@v3

      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: 21.3.0
          java: java17

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - uses: crazy-max/ghaction-import-gpg@v4.3.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - run: |
          chmod +x gradlew
          ./gradlew build

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            plugin/build/libs/FakePlayerPlugin.jar
